### ISSUE TITLE
Develop model / table to store Food Data (master data)

### ISSUE THREAD

**Issue by chrisfernandes123** [neilfr/project3#4]
Recommended columns include: Custom Food Number, Custom Food Name, Food Name, Food Category, Weight in g, Energy in kcal, Energy in kJ and Potassium in mg.

I think we need the Custom Food Number and / or Custom Food Name column so that the user can enter their own reference number i.e. reference number 69 is 2% milk under “Juices”, etc.  This would be in case the user has their own food reference identifiers memorized from a previous system, etc.

**Comment by neilfr** [comment]
check if I added a food alias
