### ISSUE TITLE
Develop model / table to store Custom User and Food data

### ISSUE THREAD

**Issue by chrisfernandes123** [neilfr/project3#5]
This relates to image 20190216_115710.jpg from Neil.  

This will allow the user to setup their own common consumption quantities of food based on the standard measure provide by the food master data.  This will allow the user to efficiently add food based on their common consumption quantities to meals. 

This will also allow to create custom food categories i.e. “Juices”, “Fish”, etc.

**Comment by neilfr** [comment]
done
